#FFServer.conf
            
Port 8091
RTSPPort 8090
BindAddress 0.0.0.0
MaxClients 1000
MaxBandwidth 1000000
CustomLog -
NoDaemon
<Feed stream.ffm>
    File /tmp/stream.ffm
    Truncate
    FileMaxSize 100M
    ACL allow 127.0.0.1
</Feed>
<Stream live.mp3>
    Feed stream.ffm
    Format rtp
    NoLoop
    NoVideo
    Metadata title "IFZ Live Stream"
    AVOptionAudio flags +global_header
    AudioCodec libmp3lame
    AudioBitRate 320
    AudioChannels 2
    AudioSampleRate 48000
</Stream>

<Stream stat.html>
    Format status
    # Only allow local people to get the status
    ACL allow localhost
    ACL allow 192.168.0.0 192.168.255.255
</Stream>
